name: check PRs for merge conflicts

on:
    workflow_dispatch:
    push:
        branches:
          - 'maint-*'
          - 'rfc/new-abi*'

permissions:
    pull-requests: write

jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: nokamoto/merge-conflict-action@v0.0.4
              with:
                owner: X11Libre
                repo: xserver
                token: ${{ secrets.GITHUB_TOKEN }}
